FROM python:3.12-slim

ARG GEMINI_API_KEY=""
ARG GEMINI_MODEL=""
ARG GOOGLE_API_KEY=""
ARG FIREWORKS_API_KEY=""
ARG FIREWORKS_BASE_URL=""
ARG FIREWORKS_VISION_MODEL=""
ARG FIREWORKS_FALLBACK_VISION_MODEL=""
ARG OPENROUTER_API_KEY=""
ARG OPENROUTER_MODEL=""
ARG GEMMACLIP_PROVIDER=""
ARG GEMMACLIP_AUDIO_MODE="auto"
ARG FIREWORKS_GEMMA_VISUAL_MODEL=""
ARG FIREWORKS_GEMMA_AUDIO_VISUAL_MODEL=""
ARG FIREWORKS_GEMMA_CAPTION_MODEL=""
ARG GOOGLE_GEMMA_VISUAL_MODEL=""
ARG GOOGLE_GEMMA_AUDIO_VISUAL_MODEL=""
ARG GOOGLE_GEMMA_CAPTION_MODEL=""
ARG GEMMACLIP_AUDIO_MAX_SECONDS="30"
ARG GEMMACLIP_AUDIO_SAMPLE_RATE="16000"
ARG GEMMACLIP_AUDIO_MIN_RMS="0.01"
ARG GEMMACLIP_AUDIO_MIN_REMAINING_SECONDS="170"
ARG GEMMACLIP_ROUTED_EVIDENCE_TEMPERATURE="0.0"
ARG GEMMACLIP_ROUTED_CAPTION_TEMPERATURE="0.4"
ARG GEMMACLIP_ROUTED_REPAIR_TEMPERATURE="0.25"
ARG GEMMACLIP_ROUTED_SINGLE_CALL_TEMPERATURE="0.4"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

ENV GEMINI_API_KEY=${GEMINI_API_KEY} \
    GOOGLE_API_KEY=${GOOGLE_API_KEY} \
    FIREWORKS_API_KEY=${FIREWORKS_API_KEY} \
    FIREWORKS_BASE_URL=${FIREWORKS_BASE_URL} \
    FIREWORKS_VISION_MODEL=${FIREWORKS_VISION_MODEL} \
    FIREWORKS_FALLBACK_VISION_MODEL=${FIREWORKS_FALLBACK_VISION_MODEL} \
    GEMINI_MODEL=${GEMINI_MODEL} \
    OPENROUTER_API_KEY=${OPENROUTER_API_KEY} \
    OPENROUTER_MODEL=${OPENROUTER_MODEL} \
    GEMMACLIP_PROVIDER=${GEMMACLIP_PROVIDER} \
    GEMMACLIP_AUDIO_MODE=${GEMMACLIP_AUDIO_MODE} \
    FIREWORKS_GEMMA_VISUAL_MODEL=${FIREWORKS_GEMMA_VISUAL_MODEL} \
    FIREWORKS_GEMMA_AUDIO_VISUAL_MODEL=${FIREWORKS_GEMMA_AUDIO_VISUAL_MODEL} \
    FIREWORKS_GEMMA_CAPTION_MODEL=${FIREWORKS_GEMMA_CAPTION_MODEL} \
    GOOGLE_GEMMA_VISUAL_MODEL=${GOOGLE_GEMMA_VISUAL_MODEL} \
    GOOGLE_GEMMA_AUDIO_VISUAL_MODEL=${GOOGLE_GEMMA_AUDIO_VISUAL_MODEL} \
    GOOGLE_GEMMA_CAPTION_MODEL=${GOOGLE_GEMMA_CAPTION_MODEL} \
    GEMMACLIP_AUDIO_MAX_SECONDS=${GEMMACLIP_AUDIO_MAX_SECONDS} \
    GEMMACLIP_AUDIO_SAMPLE_RATE=${GEMMACLIP_AUDIO_SAMPLE_RATE} \
    GEMMACLIP_AUDIO_MIN_RMS=${GEMMACLIP_AUDIO_MIN_RMS} \
    GEMMACLIP_AUDIO_MIN_REMAINING_SECONDS=${GEMMACLIP_AUDIO_MIN_REMAINING_SECONDS} \
    GEMMACLIP_ROUTED_EVIDENCE_TEMPERATURE=${GEMMACLIP_ROUTED_EVIDENCE_TEMPERATURE} \
    GEMMACLIP_ROUTED_CAPTION_TEMPERATURE=${GEMMACLIP_ROUTED_CAPTION_TEMPERATURE} \
    GEMMACLIP_ROUTED_REPAIR_TEMPERATURE=${GEMMACLIP_ROUTED_REPAIR_TEMPERATURE} \
    GEMMACLIP_ROUTED_SINGLE_CALL_TEMPERATURE=${GEMMACLIP_ROUTED_SINGLE_CALL_TEMPERATURE}

ENV GEMMACLIP_DISABLE_VERIFIER=true

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg ca-certificates coreutils \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md /app/
COPY src /app/src

RUN pip install --no-cache-dir .

ENTRYPOINT ["/bin/sh", "-c", "timeout --signal=TERM --kill-after=5s 590s python -m gemmaclip.main; status=$?; [ \"$status\" -eq 124 ] && exit 0; exit \"$status\""]
