/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as LabRouteImport } from './routes/lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRunIdRouteImport } from './routes/lab.$runId'
import { Route as LabRunIdIndexRouteImport } from './routes/lab.$runId.index'
import { Route as LabRunIdVideoRouteImport } from './routes/lab.$runId.video'
import { Route as LabRunIdFramesRouteImport } from './routes/lab.$runId.frames'
import { Route as LabRunIdEvidenceRouteImport } from './routes/lab.$runId.evidence'
import { Route as LabRunIdCompareRouteImport } from './routes/lab.$runId.compare'
import { Route as LabRunIdCaptionsRouteImport } from './routes/lab.$runId.captions'
import { Route as LabRunIdAudioRouteImport } from './routes/lab.$runId.audio'

const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRunIdRoute = LabRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => LabRoute,
} as any)
const LabRunIdIndexRoute = LabRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRunIdRoute,
} as any)
const LabRunIdVideoRoute = LabRunIdVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => LabRunIdRoute,
} as any)
const LabRunIdFramesRoute = LabRunIdFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => LabRunIdRoute,
} as any)
const LabRunIdEvidenceRoute = LabRunIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => LabRunIdRoute,
} as any)
const LabRunIdCompareRoute = LabRunIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LabRunIdRoute,
} as any)
const LabRunIdCaptionsRoute = LabRunIdCaptionsRouteImport.update({
  id: '/captions',
  path: '/captions',
  getParentRoute: () => LabRunIdRoute,
} as any)
const LabRunIdAudioRoute = LabRunIdAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => LabRunIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/quick': typeof QuickRoute
  '/lab/$runId': typeof LabRunIdRouteWithChildren
  '/lab/$runId/audio': typeof LabRunIdAudioRoute
  '/lab/$runId/captions': typeof LabRunIdCaptionsRoute
  '/lab/$runId/compare': typeof LabRunIdCompareRoute
  '/lab/$runId/evidence': typeof LabRunIdEvidenceRoute
  '/lab/$runId/frames': typeof LabRunIdFramesRoute
  '/lab/$runId/video': typeof LabRunIdVideoRoute
  '/lab/$runId/': typeof LabRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/quick': typeof QuickRoute
  '/lab/$runId/audio': typeof LabRunIdAudioRoute
  '/lab/$runId/captions': typeof LabRunIdCaptionsRoute
  '/lab/$runId/compare': typeof LabRunIdCompareRoute
  '/lab/$runId/evidence': typeof LabRunIdEvidenceRoute
  '/lab/$runId/frames': typeof LabRunIdFramesRoute
  '/lab/$runId/video': typeof LabRunIdVideoRoute
  '/lab/$runId': typeof LabRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/quick': typeof QuickRoute
  '/lab/$runId': typeof LabRunIdRouteWithChildren
  '/lab/$runId/audio': typeof LabRunIdAudioRoute
  '/lab/$runId/captions': typeof LabRunIdCaptionsRoute
  '/lab/$runId/compare': typeof LabRunIdCompareRoute
  '/lab/$runId/evidence': typeof LabRunIdEvidenceRoute
  '/lab/$runId/frames': typeof LabRunIdFramesRoute
  '/lab/$runId/video': typeof LabRunIdVideoRoute
  '/lab/$runId/': typeof LabRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/quick'
    | '/lab/$runId'
    | '/lab/$runId/audio'
    | '/lab/$runId/captions'
    | '/lab/$runId/compare'
    | '/lab/$runId/evidence'
    | '/lab/$runId/frames'
    | '/lab/$runId/video'
    | '/lab/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab'
    | '/quick'
    | '/lab/$runId/audio'
    | '/lab/$runId/captions'
    | '/lab/$runId/compare'
    | '/lab/$runId/evidence'
    | '/lab/$runId/frames'
    | '/lab/$runId/video'
    | '/lab/$runId'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/quick'
    | '/lab/$runId'
    | '/lab/$runId/audio'
    | '/lab/$runId/captions'
    | '/lab/$runId/compare'
    | '/lab/$runId/evidence'
    | '/lab/$runId/frames'
    | '/lab/$runId/video'
    | '/lab/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
  QuickRoute: typeof QuickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$runId': {
      id: '/lab/$runId'
      path: '/$runId'
      fullPath: '/lab/$runId'
      preLoaderRoute: typeof LabRunIdRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/$runId/': {
      id: '/lab/$runId/'
      path: '/'
      fullPath: '/lab/$runId/'
      preLoaderRoute: typeof LabRunIdIndexRouteImport
      parentRoute: typeof LabRunIdRoute
    }
    '/lab/$runId/video': {
      id: '/lab/$runId/video'
      path: '/video'
      fullPath: '/lab/$runId/video'
      preLoaderRoute: typeof LabRunIdVideoRouteImport
      parentRoute: typeof LabRunIdRoute
    }
    '/lab/$runId/frames': {
      id: '/lab/$runId/frames'
      path: '/frames'
      fullPath: '/lab/$runId/frames'
      preLoaderRoute: typeof LabRunIdFramesRouteImport
      parentRoute: typeof LabRunIdRoute
    }
    '/lab/$runId/evidence': {
      id: '/lab/$runId/evidence'
      path: '/evidence'
      fullPath: '/lab/$runId/evidence'
      preLoaderRoute: typeof LabRunIdEvidenceRouteImport
      parentRoute: typeof LabRunIdRoute
    }
    '/lab/$runId/compare': {
      id: '/lab/$runId/compare'
      path: '/compare'
      fullPath: '/lab/$runId/compare'
      preLoaderRoute: typeof LabRunIdCompareRouteImport
      parentRoute: typeof LabRunIdRoute
    }
    '/lab/$runId/captions': {
      id: '/lab/$runId/captions'
      path: '/captions'
      fullPath: '/lab/$runId/captions'
      preLoaderRoute: typeof LabRunIdCaptionsRouteImport
      parentRoute: typeof LabRunIdRoute
    }
    '/lab/$runId/audio': {
      id: '/lab/$runId/audio'
      path: '/audio'
      fullPath: '/lab/$runId/audio'
      preLoaderRoute: typeof LabRunIdAudioRouteImport
      parentRoute: typeof LabRunIdRoute
    }
  }
}

interface LabRunIdRouteChildren {
  LabRunIdAudioRoute: typeof LabRunIdAudioRoute
  LabRunIdCaptionsRoute: typeof LabRunIdCaptionsRoute
  LabRunIdCompareRoute: typeof LabRunIdCompareRoute
  LabRunIdEvidenceRoute: typeof LabRunIdEvidenceRoute
  LabRunIdFramesRoute: typeof LabRunIdFramesRoute
  LabRunIdVideoRoute: typeof LabRunIdVideoRoute
  LabRunIdIndexRoute: typeof LabRunIdIndexRoute
}

const LabRunIdRouteChildren: LabRunIdRouteChildren = {
  LabRunIdAudioRoute: LabRunIdAudioRoute,
  LabRunIdCaptionsRoute: LabRunIdCaptionsRoute,
  LabRunIdCompareRoute: LabRunIdCompareRoute,
  LabRunIdEvidenceRoute: LabRunIdEvidenceRoute,
  LabRunIdFramesRoute: LabRunIdFramesRoute,
  LabRunIdVideoRoute: LabRunIdVideoRoute,
  LabRunIdIndexRoute: LabRunIdIndexRoute,
}

const LabRunIdRouteWithChildren = LabRunIdRoute._addFileChildren(
  LabRunIdRouteChildren,
)

interface LabRouteChildren {
  LabRunIdRoute: typeof LabRunIdRouteWithChildren
}

const LabRouteChildren: LabRouteChildren = {
  LabRunIdRoute: LabRunIdRouteWithChildren,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
  QuickRoute: QuickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
